import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import { useCallback, useEffect } from "react";
import { useRouter } from "next/router";

const Main: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="../assets/favicon-32x32.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-veryDarkGrey">
        <AuthShowcase />
      </main>
    </>
  );
};

export default Main;

const AuthShowcase: React.FC = () => {
  const router = useRouter();
  const { data: sessionData } = useSession();

  const getEnvAndNav = useCallback(async () => {
    if (process.env.NODE_ENV === "development") {
      await router.push("http://localhost:3000/home");
    } else {
      await router.push("https://eylon-kanban.vercel.app/home");
    }
  }, []);

  useEffect(() => {
    if (sessionData) {
      void getEnvAndNav();
    }
  }, [sessionData]);

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={() => {
          void signIn("discord", {
            callbackUrl: "/home",
          });
        }}
      >
        Login
      </button>
    </div>
  );
};
